// eslint-disable @typescript-eslint/no-require-imports
const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  appUrl: ['/apps/frontend-assets'],
  debug: true,
  useProxy: true,
  proxyVerbose: true,
  sassPrefix: '.frontend-assets, .frontendAssets',
  frontendCRDPath: path.resolve(__dirname, 'config', 'frontend.yml'),
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: path.resolve(__dirname, 'src', '**/*.svg'),
          to: ({ absoluteFilename, context }) => {
            // Ensure the destination path of icons is relative to the context
            const dest = `${context}${absoluteFilename.replace(context, '').replace('/src', '/dist')}`;
            return dest;
          },
        },
      ],
    }),
  ],
  // do not modify this object, it is generated by a script to automatically generate the icons

  /* eslint-disable prettier/prettier */
  moduleFederation: {
      exposes: {
  "./TechnologyIcons3scaleApiManagement": path.resolve(__dirname, 'src', 'new', 'technology-icons/3scale-api-management.tsx'),
  "./TechnologyIconsAcmForKubernetes": path.resolve(__dirname, 'src', 'new', 'technology-icons/acm-for-kubernetes.tsx')
},
    },
  /* eslint-enable prettier/prettier */
};
