// eslint-disable @typescript-eslint/no-require-imports
const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  appUrl: ['/apps/frontend-assets'],
  debug: true,
  useProxy: true,
  proxyVerbose: true,
  sassPrefix: '.frontend-assets, .frontendAssets',
  frontendCRDPath: path.resolve(__dirname, 'config', 'frontend.yml'),
  plugins: [
    new CopyPlugin({
      patterns: [
        {
          from: path.resolve(__dirname, 'src', '**/*.{svg,png,jpg,jpeg}'),
          to: ({ absoluteFilename, context }) => {
            // Ensure the destination path of icons is relative to the context
            const dest = `${context}${absoluteFilename.replace(context, '').replace('/src', '/dist')}`;
            return dest;
          },
        },
      ],
    }),
  ],
  // do not modify this object, it is generated by a script to automatically generate the icons

  /* eslint-disable prettier/prettier */
  moduleFederation: {
    exposes: {
      "./PartnersAws": path.resolve(__dirname, 'src', 'partners/aws.tsx'),
      "./TechnologyIcons3scaleApiManagement": path.resolve(__dirname, 'src', 'technology-icons/3scale-api-management.tsx'),
      "./TechnologyIconsAcmForKubernetes": path.resolve(__dirname, 'src', 'technology-icons/acm-for-kubernetes.tsx'),
      "./TechnologyIconsAcs": path.resolve(__dirname, 'src', 'technology-icons/acs.tsx'),
      "./TechnologyIconsAmq": path.resolve(__dirname, 'src', 'technology-icons/amq.tsx'),
      "./TechnologyIconsAnsible": path.resolve(__dirname, 'src', 'technology-icons/ansible.tsx'),
      "./TechnologyIconsAnsibleAutomationHubHosted": path.resolve(__dirname, 'src', 'technology-icons/ansible-automation-hub-hosted.tsx'),
      "./TechnologyIconsAnsibleAutomationPlatformOperator": path.resolve(__dirname, 'src', 'technology-icons/ansible-automation-platform-operator.tsx'),
      "./TechnologyIconsAnsibleContentCollections": path.resolve(__dirname, 'src', 'technology-icons/ansible-content-collections.tsx'),
      "./TechnologyIconsAnsibleContentTools": path.resolve(__dirname, 'src', 'technology-icons/ansible-content-tools.tsx'),
      "./TechnologyIconsAnsibleCore": path.resolve(__dirname, 'src', 'technology-icons/ansible-core.tsx'),
      "./TechnologyIconsAnsiblePlaybooks": path.resolve(__dirname, 'src', 'technology-icons/ansible-playbooks.tsx'),
      "./TechnologyIconsAnsibleRulebook": path.resolve(__dirname, 'src', 'technology-icons/ansible-rulebook.tsx'),
      "./TechnologyIconsApacheKafka": path.resolve(__dirname, 'src', 'technology-icons/apache-kafka.tsx'),
      "./TechnologyIconsAppServices": path.resolve(__dirname, 'src', 'technology-icons/app-services.tsx'),
      "./TechnologyIconsAutomationContentNavigator": path.resolve(__dirname, 'src', 'technology-icons/automation-content-navigator.tsx'),
      "./TechnologyIconsAutomationController": path.resolve(__dirname, 'src', 'technology-icons/automation-controller.tsx'),
      "./TechnologyIconsAutomationExecutionEnvironments": path.resolve(__dirname, 'src', 'technology-icons/automation-execution-environments.tsx'),
      "./TechnologyIconsAutomationMesh": path.resolve(__dirname, 'src', 'technology-icons/automation-mesh.tsx'),
      "./TechnologyIconsBuildOfApacheCamel": path.resolve(__dirname, 'src', 'technology-icons/build-of-apache-camel.tsx'),
      "./TechnologyIconsBuildOfOpenTelemetry": path.resolve(__dirname, 'src', 'technology-icons/build-of-open-telemetry.tsx'),
      "./TechnologyIconsBuildOfQuarkus": path.resolve(__dirname, 'src', 'technology-icons/build-of-quarkus.tsx'),
      "./TechnologyIconsBuildsForOpenshift": path.resolve(__dirname, 'src', 'technology-icons/builds-for-openshift.tsx'),
      "./TechnologyIconsComplianceOperator": path.resolve(__dirname, 'src', 'technology-icons/compliance-operator.tsx'),
      "./TechnologyIconsCustomMetricsAutoscaler": path.resolve(__dirname, 'src', 'technology-icons/custom-metrics-autoscaler.tsx'),
      "./TechnologyIconsDataScience": path.resolve(__dirname, 'src', 'technology-icons/data-science.tsx'),
      "./TechnologyIconsDependencyAnalytics": path.resolve(__dirname, 'src', 'technology-icons/dependency-analytics.tsx'),
      "./TechnologyIconsDeveloperHub": path.resolve(__dirname, 'src', 'technology-icons/developer-hub.tsx'),
      "./TechnologyIconsDeviceEdge": path.resolve(__dirname, 'src', 'technology-icons/device-edge.tsx'),
      "./TechnologyIconsDistributedTracing": path.resolve(__dirname, 'src', 'technology-icons/distributed-tracing.tsx'),
      "./TechnologyIconsEdge": path.resolve(__dirname, 'src', 'technology-icons/edge.tsx'),
      "./TechnologyIconsEventDrivenAnsibleController": path.resolve(__dirname, 'src', 'technology-icons/event-driven-ansible-controller.tsx'),
      "./TechnologyIconsExecutionEnvironmentBuilder": path.resolve(__dirname, 'src', 'technology-icons/execution-environment-builder.tsx'),
      "./TechnologyIconsFileIntegrityOperator": path.resolve(__dirname, 'src', 'technology-icons/file-integrity-operator.tsx'),
      "./TechnologyIconsIam": path.resolve(__dirname, 'src', 'technology-icons/iam.tsx'),
      "./TechnologyIconsImageMode": path.resolve(__dirname, 'src', 'technology-icons/image-mode.tsx'),
      "./TechnologyIconsInfraredIntelligenceFeature": path.resolve(__dirname, 'src', 'technology-icons/infrared-intelligence-feature.tsx'),
      "./TechnologyIconsInfrastructureOperatorForOpenshift": path.resolve(__dirname, 'src', 'technology-icons/infrastructure-operator-for-openshift.tsx'),
      "./TechnologyIconsInsights": path.resolve(__dirname, 'src', 'technology-icons/insights.tsx'),
      "./TechnologyIconsIntegrations": path.resolve(__dirname, 'src', 'technology-icons/integrations.tsx'),
      "./TechnologyIconsJbossEap": path.resolve(__dirname, 'src', 'technology-icons/jboss-eap.tsx'),
      "./TechnologyIconsLearningResources": path.resolve(__dirname, 'src', 'technology-icons/learning-resources.tsx'),
      "./TechnologyIconsLightspeed": path.resolve(__dirname, 'src', 'technology-icons/lightspeed.tsx'),
      "./TechnologyIconsMigrationToolkit": path.resolve(__dirname, 'src', 'technology-icons/migration-toolkit.tsx'),
      "./TechnologyIconsNotifications": path.resolve(__dirname, 'src', 'technology-icons/notifications.tsx'),
      "./TechnologyIconsOpenshift": path.resolve(__dirname, 'src', 'technology-icons/openshift.tsx'),
      "./TechnologyIconsOpenshiftAi": path.resolve(__dirname, 'src', 'technology-icons/openshift-ai.tsx'),
      "./TechnologyIconsOpenshiftApiDesigner": path.resolve(__dirname, 'src', 'technology-icons/openshift-api-designer.tsx'),
      "./TechnologyIconsOpenshiftConnectors": path.resolve(__dirname, 'src', 'technology-icons/openshift-connectors.tsx'),
      "./TechnologyIconsOpenshiftDatabaseAccess": path.resolve(__dirname, 'src', 'technology-icons/openshift-database-access.tsx'),
      "./TechnologyIconsOpenshiftDevSpaces": path.resolve(__dirname, 'src', 'technology-icons/openshift-dev-spaces.tsx'),
      "./TechnologyIconsOpenshiftGitOps": path.resolve(__dirname, 'src', 'technology-icons/openshift-git-ops.tsx'),
      "./TechnologyIconsOpenshiftPipelines": path.resolve(__dirname, 'src', 'technology-icons/openshift-pipelines.tsx'),
      "./TechnologyIconsOpenshiftSandboxedContainers": path.resolve(__dirname, 'src', 'technology-icons/openshift-sandboxed-containers.tsx'),
      "./TechnologyIconsOpenshiftServerless": path.resolve(__dirname, 'src', 'technology-icons/openshift-serverless.tsx'),
      "./TechnologyIconsOpenshiftServiceMesh": path.resolve(__dirname, 'src', 'technology-icons/openshift-service-mesh.tsx'),
      "./TechnologyIconsOpenshiftServiceRegistry": path.resolve(__dirname, 'src', 'technology-icons/openshift-service-registry.tsx'),
      "./TechnologyIconsOpenshiftSmartEvents": path.resolve(__dirname, 'src', 'technology-icons/openshift-smart-events.tsx'),
      "./TechnologyIconsOpenshiftVirtualization": path.resolve(__dirname, 'src', 'technology-icons/openshift-virtualization.tsx'),
      "./TechnologyIconsOpenstackPlatform": path.resolve(__dirname, 'src', 'technology-icons/openstack-platform.tsx'),
      "./TechnologyIconsPlaceholder1": path.resolve(__dirname, 'src', 'technology-icons/placeholder-1.tsx'),
      "./TechnologyIconsPlaceholder2": path.resolve(__dirname, 'src', 'technology-icons/placeholder-2.tsx'),
      "./TechnologyIconsPrivateAutomationHub": path.resolve(__dirname, 'src', 'technology-icons/private-automation-hub.tsx'),
      "./TechnologyIconsQuayIo": path.resolve(__dirname, 'src', 'technology-icons/quay-io.tsx'),
      "./TechnologyIconsRh": path.resolve(__dirname, 'src', 'technology-icons/rh.tsx'),
      "./TechnologyIconsRhel": path.resolve(__dirname, 'src', 'technology-icons/rhel.tsx'),
      "./TechnologyIconsRhelLinuxForWorkstations": path.resolve(__dirname, 'src', 'technology-icons/rhel-linux-for-workstations.tsx'),
      "./TechnologyIconsRhtap": path.resolve(__dirname, 'src', 'technology-icons/rhtap.tsx'),
      "./TechnologyIconsRuntimes": path.resolve(__dirname, 'src', 'technology-icons/runtimes.tsx'),
      "./TechnologyIconsSatellite": path.resolve(__dirname, 'src', 'technology-icons/satellite.tsx'),
      "./TechnologyIconsSecurityProfileOperator": path.resolve(__dirname, 'src', 'technology-icons/security-profile-operator.tsx'),
      "./TechnologyIconsSettings": path.resolve(__dirname, 'src', 'technology-icons/settings.tsx'),
      "./TechnologyIconsSingleSignOn": path.resolve(__dirname, 'src', 'technology-icons/single-sign-on.tsx'),
      "./TechnologyIconsSubscriptions": path.resolve(__dirname, 'src', 'technology-icons/subscriptions.tsx'),
      "./TechnologyIconsTrustedArtifact": path.resolve(__dirname, 'src', 'technology-icons/trusted-artifact.tsx'),
      "./TechnologyIconsTrustedArtifactSigner": path.resolve(__dirname, 'src', 'technology-icons/trusted-artifact-signer.tsx'),
      "./TechnologyIconsTrustedContent1": path.resolve(__dirname, 'src', 'technology-icons/trusted-content-1.tsx'),
      "./TechnologyIconsTrustedContent2": path.resolve(__dirname, 'src', 'technology-icons/trusted-content-2.tsx')
    },
  },
  /* eslint-enable prettier/prettier */
};

