# yaml-language-server: $schema=https://raw.githubusercontent.com/RedHatInsights/frontend-components/refs/heads/master/packages/config-utils/src/feo/spec/frontend-crd.schema.json
---
apiVersion: v1
kind: Template
metadata:
  name: frontend-assets
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: frontend-assets
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/frontend-assets
      title: frontend-assets
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      module:
        manifestLocation: "/frontend-assets/fed-mods.json"
        modules: []
      frontend:
        paths:
          - /apps/frontend-assets
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/rh-platform-experien-tenant/frontend-assets
