apiVersion: v1
kind: Template
metadata:
  name: frontend-assets
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: frontend-assets
    spec:
      envName: ${ENV_NAME}
      deploymentRepo: https://github.com/RedHatInsights/frontend-assets
      title: frontend-assets
      image: ${IMAGE}:${IMAGE_TAG}
      API:
        versions:
          - v1
      module:
        manifestLocation: "/frontend-assets/fed-mods.json"
        modules:
          - id: "frontend-assets"
            module: "./RootApp"
            routes:
              - pathname: /frontend-assets
      frontend:
        paths:
          - /apps/frontend-assets
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/redhat-services-prod/rh-platform-experien-tenant/frontend-assets
